name: "Family companion"
description: "Family companion description"
version: "0.0.1a"
slug: "fam_comp"
homeassistant_api: true
init: false
ingress: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
