name: "Family companion"
description: "Simple task manager addon for home assistant"
version: 0.1.5a
slug: "fam_comp"
homeassistant_api: true
init: false
ingress: true
panel_admin: false
url: https://github.com/HolyNoodle/family-companion
arch:
  - amd64
options:
  locale: en
  logLevel: 1
schema:
  locale: str
  notificationUrl: str?
  logLevel: "int(0,4)"
