name: "Family companion"
description: "Simple task manager addon for home assistant"
version: 0.2.2b
slug: "fam_comp"
homeassistant_api: true
init: false
ingress: true
panel_admin: false
panel_icon: mdi:list-box-outline
url: https://github.com/HolyNoodle/family-companion
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - armv7
options:
  locale: en
  logLevel: 1
schema:
  locale: str
  notificationUrl: str?
  logLevel: "int(0,4)"
