name: "Family companion"
description: "Simple task manager addon for home assistant"
version: "0.0.13a"
slug: "fam_comp"
homeassistant_api: true
init: false
ingress: true
url: https://github.com/HolyNoodle/family-companion
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
