FROM node:alpine

RUN npm i -g pnpm

RUN yarn global add turbo

RUN apk update
RUN apk add bash nginx 
RUN mkdir -p /run/nginx

COPY ./ingress.conf /etc/nginx/nginx.conf

WORKDIR /app

EXPOSE 8099

ENV STORAGE_PATH /data/db
ENV SUPERVISOR_URL supervisor/core

CMD [ "/bin/bash", "-c", "nginx -g \"daemon off;error_log /dev/stdout info;\" & turbo start:dev" ]
