name: Build
on:
  push:
    main:
      path: version

jobs:
  build:
    timeout-minutes: 90
    runs-on: ubuntu-latest
    name: Build docker imgaes

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set variables
        run: |
          VER=$(cat version)
          echo "VERSION=$VER" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags:
            - ${{ secrets.DOCKERHUB_USERNAME }}/family-companion:latest
            - ${{ secrets.DOCKERHUB_USERNAME }}/family-companion:${{ env.VERSION }}
          platforms: linux/amd64,linux/arm64,linux/aarch64

      - name: Bump version
        run: sh ./bump_version.sh
