name: Build
on:
  push:
    branches:
      - main
    path: 
      - VERSION

jobs:
  build:
    timeout-minutes: 90
    runs-on: ubuntu-latest
    name: Build docker imgaes

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set variables
        run: |
          VER=$(cat ./VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.base
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/family-companion:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/family-companion:${{ env.VERSION }}
          platforms: linux/amd64,linux/arm64,linux/arm/v8,linux/arm/v7,linux/arm/v6

      - name: Bump version
        run: | 
          git config --global user.name "Continuous Integration"
          git config --global user.email "ci@holynoodle.github.com"
          sh ./bump_version.sh
