name: Build
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - Dockerfile.base
jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    name: install

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Test docker prod build
        run: docker buildx build . -f Dockerfile.base