name: Pull request
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  install:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    name: install

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 8.2.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test